### PR TITLE
Remove CSM

### PR DESCRIPTION
**Pull request by GuestSneezeOSDev**
FakeCSM was developed for Mapbase not the standard Source SDK 2013

### CODE REVIEW

**Comment by ThePixelMoon** [comment]
image

**Comment by GuestSneezeOSDev** [comment]
I will use my new (coming soon) lighting system in the near future

**Comment by GuestSneezeOSDev** [comment]
gay

**Comment by GuestSneezeOSDev** [comment]
💀 
Screenshot 2024-09-06 191120

**Pull request merged**
